### PR TITLE
test: refactored tests to run independently and for improved organization

### LINKED ISSUE #4: Incorrect usage of testing framework
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ * ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Tests in this project are written in such a way that is:

a) Difficult to read and maintain individual tests, and
b) Unable to report on the status of tests subsequent to those that fail.

This is because what are intended to be tests in this project are actually assertions, and what is being used as suites are actually individual tests. Example:

```typescript
/*
  'journal' should be the name of the file containing the suite of tests. Each one of the assertions below need to
  be handled by a single `test()` function, depending on how closely related they are.
*/
test('journal', (t) => {
  const result1 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`1900/01/01 transaction\n`).rawJournal
  );
  // Each instance of t.is() is an assertion, not a test. The message field should be used to display the value that failed.
  t.is(result1.transactions.length, 1, 'should have 1 parsed transaction');
  t.is(result1.accounts.length, 0, 'should have 0 parsed account directives');
  t.is(result1.prices.length, 0, 'should have 0 parsed price directives');

  // Additional setup after a series of assertions is a sign that the test should be split up
  const result2 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`account Account:Test\n`).rawJournal
  );
  t.is(result2.transactions.length, 0, 'should have 0 parsed transactions');
  t.is(result2.accounts.length, 1, 'should have 1 parsed account directive');
  t.is(result2.prices.length, 0, 'should have 0 parsed price directives');

  const result3 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`P 1900/01/01 CAD $1.00\n`).rawJournal
  );
  t.is(result3.transactions.length, 0, 'should have 0 parsed transactions');
  t.is(result3.accounts.length, 0, 'should have 0 parsed account directives');
  t.is(result3.prices.length, 1, 'should have 1 parsed price directive');
});
```

This way of writing tests encourages the inclusion of unrelated tests in the same file. This makes taking advantage of functions like `test.before()`, `test.beforeAll()`, `test.after()`, and `test.afterAll()` difficult, as you would have monolithic setup and teardown implemented to handle the various requirements of the different tests that are functioning as suites.

The way tests are currently written, it would be beneficial to put each one in an individual file. Then split out the assertions into individual `test()` functions, where the message of the assertion becomes the title of the test. Writing tests this way enables the developer to see if multiple tests fail at the same time.

Currently, with the assertions written as tests, when one fails, the whole 'suite' fails without running further tests. This makes it difficult to determine the true effect of a change as potential issues are hidden. Here's one way you can implement the above test:

```typescript
// journal.test.ts, contained in folder 'raw_to_cooked_visitor'
test.before(t => {
  t.context = {
    result1: RawToCookedVisitor.journal(
      parseLedgerToRaw(`1900/01/01 transaction\n`).rawJournal
    ),
    result2: RawToCookedVisitor.journal(
      parseLedgerToRaw(`account Account:Test\n`).rawJournal
    ),
    result3: RawToCookedVisitor.journal(
      parseLedgerToRaw(`P 1900/01/01 CAD $1.00\n`).rawJournal
    )
  };
});

test('should have 1 parsed transaction', (t) => {
  t.is(t.context.result1.transactions.length, 1, );
});

test('should have 0 parsed account directives', (t) => {
  t.is(t.context.result1.accounts.length, 0, );
});

test('should have 0 parsed price directives', (t) => {
  t.is(t.context.result1.prices.length, 0, );
});

test('should have 0 parsed transactions', (t) => {
  t.is(t.context.result2.transactions.length, 0, );
});

test('should have 1 parsed account directive', (t) => {
  t.is(t.context.result2.accounts.length, 1, );
});

test('should have 0 parsed price directives', (t) => {
  t.is(t.context.result2.prices.length, 0, );
});

test('should have 0 parsed transactions', (t) => {
  t.is(t.context.result3.transactions.length, 0, );
});

test('should have 0 parsed account directives', (t) => {
  t.is(t.context.result3.accounts.length, 0, );
});

test('should have 1 parsed price directive', (t) => {
  t.is(t.context.result3.prices.length, 1, );
});
```

Now we would be able to determine if multiple tests fail or not and get better insight as to the impact of changes. All tests ~~except for those in lexer.test.ts~~ need to be refactored similar to the above example so that we can start using the testing framework correctly, and also take advantage of additional testing features.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

[AVA documentation](https://github.com/avajs/ava/blob/e27183a9e8f6bb5ea12936f133796846af945154/docs/01-writing-tests.md)

### PR DESCRIPTION
**Pull request by darylwright**
Prior to this change, many tests in this project did not run independently. This made it difficult to diagnose issues resulting in changes to the source as many test results were hidden. All tests in this project have been rewritten such that they now run independently from each other. Titles have been added to tests that describe the behaviour being tested. Due to the increased number of tests, running the unit test script now takes longer than before, which is expected.

Fixes #4

### CODE REVIEW

**Comment by jonestristand** [comment]
What an incredible amount of work - thank you! I have merged the changes and updated the version number to 0.3.0. 

There are also available test suites of hledger/ledger journal files - I was planning to add one of these as part of the testing process for the library as well - thoughts?

**Comment by darylwright** [comment]
> What an incredible amount of work - thank you! I have merged the changes and updated the version number to 0.3.0.
> 
> There are also available test suites of hledger/ledger journal files - I was planning to add one of these as part of the testing process for the library as well - thoughts?

I haven't looked too deeply into hledger's test suite. My first thought is that it might take less effort to write tests from the hledger spec, rather than dive into the source. The source code could be a good resource though, but it will be difficult to actually use it here. I'll admit I'm a bit biased as part of my reason for contributing to this project is so I can avoid learning Haskell as long as possible.

**Comment by jonestristand** [comment]
> so I can avoid learning Haskell as long as possible.

Right there with you... Any other features you're missing at the moment?

**Comment by darylwright** [comment]
I'm currently working on implementing the commodity directive and format subdirective. I made some design changes in that branch as I was frequently encountering circular imports, leaving some types as undefined before they get a chance to be loaded. It'll probably be a while until those changes are ready to be reviewed.

**Comment by jonestristand** [comment]
Sounds good. Out of curiousity are you planning to use this to write a tool to automatically import commodity prices?

**Comment by darylwright** [comment]
That would be nice, and I do actually want to automate that. I have a long term project I'm planning to build that will make hledger more accessible to non-developers. As part of that plan, I'd like to see a conversion to the unified AST format so this can take advantage of its plugin environment. This could enable things like converting an hledger journal to HTML, for instance.

**Pull request merged**
