### PR TITLE
feat: fully implemented amount formats as per hledger spec

### LINKED ISSUE #6: Full implementation of amounts as per hledger spec
**I'm submitting a ...**
  [ ] bug report
  [ * ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

**Summary**

As per the hledger spec, [amounts](https://hledger.org/1.30/hledger.html#amounts) can be expressed with a great level of flexibility. Currently, `hledger-parser` only implements a subset of the amount formats supported by hledger. For features like the [commodity directive](https://hledger.org/1.30/hledger.html#commodity-directive) to make sense to implement, `hledger-parser` must implement support for the full range of amount formats allowable.

For instance, the following number formats should be valid, but currently are not:

- 1 000 000.55
- 1.000.000,00
- 1 000 030,00
- 1000 000 00 000.00
- ~~1,000,000 00~~
- ~~1.000.000 00~~
- 1.000,
- 1 000.
- 1,000.
- $-1.00
- -$1
- + $1
- $-&nbsp;&nbsp;&nbsp;&nbsp;1 ; it is only necessary to store one space since, "One or more spaces between the sign and the number are acceptable when parsing (but they won't be displayed in output):" [source](https://hledger.org/1.30/hledger.html#amounts)
- - $ 1
- $ - 1

~~The only exception to the above patterns I'd suggest is that a space is invalid as a decimal mark, unless it is followed by at least one digit. This removes any ambiguity when lexing and parsing content after the amount. With a currency format like `1,000 CAD`, we wouldn't be able to distinguish if the space was the decimal mark, and there's no "space" between the number and commodity text, or otherwise. Likewise with the amount followed by a comment (`1,000 ; inline comment`).~~ *Update: spaces are invalid as decimal marks, see [documentation](https://hledger.org/1.30/hledger.html#decimal-mark-directive).*

Additionally, the formatting of the amount must be stored alongside the number, dash, and symbol. This is crucial for being able to store the representation of amounts as per the original journal. This allows us to serialize and deserialize amounts deterministically.

To summarize, there are 4 main objectives to resolve this issue:

1) Support for space and period digit group marks
2) Support for ~~space and~~ comma decimal marks
3) Support for multiple layouts of the dash/plus
4) Storage of formatting information for amounts (we have to know how amounts are formatted at every step)

### PR DESCRIPTION
**Pull request by darylwright**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  - Introduces support for more amount formats, which include inversions of commodity and sign order, and alternate digit group and decimal marks.
  - Whitespace is a significant token in amounts and are stored during lexing and parsing.
  - The plus (+) has been added as a valid sign in amounts and behaves the same as the dash (-).

- **What is the current behavior?** (You can also link to an open issue here)
  - Currently, `hledger-parser` only supports negative numbers and implicitly positive numbers (without the plus).
  - Additionally, whitespace in amounts is ignored when it should be considered a significant token.
  - No support for the plus (+) in amounts.
  - No support for alternate digit group and decimal marks.

- **What is the new behavior (if this is a feature change)?**
  - See above description.

- **Other information**:
  - N/A

fixes #6

### CODE REVIEW

**Comment by darylwright** [comment]
Prod build currently fails, still have some cleanup to do.

**Comment by darylwright** [comment]
Thanks! The parsing algorithm for the amount is particularly complex as you'll see in the diagram. I think I got it right, but could use a bit of scrutiny. Also, I tried to represent the amount in the raw type as simply as possible, but I'm open to suggestions on how to communicate the location of whitespace, commodity, and signs. For now, I just ensure the number, commodity, and sign are stored in their own respective fields, while the full expression of the amount with whitespace is just a single string field.

**Comment by jonestristand** [comment]
image
You weren't kidding :-)

**Comment by jonestristand** [comment]
This looks actually spot on to me. Well done!

**Comment by darylwright** [comment]
Awesome, thanks for the merge! This will make it easier to implement the commodity directive. It was during development of that feature where I realized I needed the correct amount parsing algorithm.

**Pull request merged**
